
# platform ,  cdh_law | cdh_user_profile
platform=cdh_law
#platform=cdh_user_profile

## job engine: spark | yarn
job.engine=spark

## extra
spark.submit.timeout=50
# seconds for max
job.check.interval=20

## stay the same , leave it ,not change!!!
yarn.submit.user=spark
mapreduce.app-submission.cross-platform=true
yarn.job.clean.interval=1