input{
    file{
        path => ["/data/media_index/media4/*.csv"]
        start_position =>"beginning"
        #sincedb_path => "/data/logstash-6.3.2/sincedb_path/order_sdp"
        }
}
filter{
    grok{
	match => ["message","%{TIMESTAMP_ISO8601:origin_time}"]
	}
    date{
	match => ["origin_time","yyyy-MM-dd HH:mm:ss"]
	target => "@timestamp"
	}
    csv{
	#autodetect_column_names => true
        quote_char => "'"
        separator => ";"
        columns => ['terminal_no','phone_no','duration','station_name','origin_time','end_time','owner_code','owner_name','vod_cat_tags','resolution','audio_lang','region','res_name','res_type','vod_title','category_name','program_title','sm_name','first_show_time']
        skip_header => true
        remove_field => ["message","path","host","@version"]
        }
   if "[" in [vod_cat_tags] {
   json {
    source => 'vod_cat_tags'
    target => 'vod_cat_tags'
    }}else{
    #source => 'vod_cat_tags'
    #target => 'vod_cat_tags'
    mutate { remove_field => "vod_cat_tags" }
   }
}
output{
    elasticsearch{
        index => "media_index%{+yyyyww}"
	document_type => "media"
        hosts => ["192.168.111.85:9200","192.168.111.86:9200","192.168.111.87:9200","192.168.111.88:9200","192.168.111.89:9200","192.168.111.90:9200"]
    }
}

