spark.master=local[*]
spark.warehouse.dir=file:///home/hadoop/export/data/user_profile_project_v2/warehouse

mysql.url=jdbc:mysql://localhost:3306/big_data_case_study?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
mysql.user=bigdata
mysql.password=BigData@123456
mysql.table.metrics=user_profile_svm_metrics
mysql.table.predictions=user_profile_svm_prediction
mysql.table.user-label=user_label

data.root=/home/hadoop/export/data/user_profile_project_v2
data.raw.path=/home/hadoop/export/data/user_profile_project_v2/raw/media_index_sample
data.processed.path=/home/hadoop/export/data/user_profile_project_v2/processed
data.output.path=/home/hadoop/export/data/user_profile_project_v2/model

model.active-duration-threshold-ms=18720000
model.max-iter=60
model.reg-param=0.01
model.validation-fraction=0.2
model.seed=20260504
