#设置程序运行环境
spring:
  profiles:
      active: dev

#用户画像页面二级标签显示个数
number: 6

#用户画像显示二级标签名称
label-name:
  label-names:
    - "消费内容"
    - "电视消费水平"
    - "宽带消费水平"
    - "电视入网程度"
    - "宽带入网程度"
    - "销售品名称"
    - "业务品牌"
    - "宽带产品带宽"
    - "用户是否挽留"
