input{
    file{
        path => ["/root/qwm/data/mmconsume_billevents_1d.csv"]
        start_position =>"beginning"
        }
}
filter{
    csv{
	autodetect_column_names => false
        separator => ";"
        columns => ["terminal_no","phone_no","fee_code","year_month","owner_name","owner_code","sm_name","should_pay","favour_fee"]
        remove_field => ["message","path","host","@version","@timestamp"]
        }
}
output{
    elasticsearch{
        index => "mmconsume_billevents"
        hosts => ["192.168.111.75:9200","192.168.111.76:9200","192.168.111.77:9200"]
    }
}
