input{
    file{
        path => ["/opt/data/userevent/mediamatch_userevent.csv"]
        start_position =>"beginning"
        sincedb_path => "/data/logstash-6.3.2/sincedb_path/userevent.sdp"
        }
}
filter{
    csv{
	      autodetect_column_names => false
        separator => ";"
        columns => ["phone_no","owner_name","run_name","run_time","sm_name","owner_code","open_time"]
        remove_field => ["message","path","host","@version","@timestamp"]
        }
}
output{
    elasticsearch{
        index => "mediamatch_userevent"
        hosts => ["192.168.111.75:9200","192.168.111.76:9200","192.168.111.77:9200"]
    }
}
