input{
    file{
        path => ["/opt/data/usermsg/mediamatch_usermsg.csv"]
        start_position =>"beginning"
        sincedb_path => "/data/logstash-6.3.2/sincedb_path/userevent.sdp"
        }
}
filter{
    csv{
	autodetect_column_names => false
        separator => ";"
        columns => ["terminal_no","phone_no","sm_name","run_name","sm_code","owner_name","owner_code","run_time","addressoj","estate_name","open_time","force"]
        remove_field => ["message","path","host","@version","@timestamp"]
        }
}
output{
    elasticsearch{
        index => "mediamatch_usermsg"
        hosts => ["192.168.111.75:9200","192.168.111.76:9200","192.168.111.77:9200"]
    }
}
