input{
    file{
        path => ["/opt/data/order_index/*.csv"]
        start_position =>"beginning"
        sincedb_path => "/data/logstash-6.3.2/sincedb_path/order.sdp"
    }
}
filter{
    csv{
        autodetect_column_names => false
        separator => ";"
        columns => ["phone_no","owner_name","optdate","prodname","sm_name","offerid","offername","business_name","owner_code","prodprcid","prodprcname","effdate","expdate","orderdate","cost","mode_time","prodstatus","run_name","orderno","offertype"]
        remove_field => ["message","path","host","@version","@timestamp"]
    }
}
output{
    elasticsearch{
        index => "order_index_v3"
        hosts => ["192.168.111.75:9200","192.168.111.76:9200","192.168.111.77:9200"]
    }
}