#db.url=jdbc:postgresql://localhost:5432/tipdm_DB
#db.url=jdbc:postgresql://192.168.0.93:5432/tipdm_hb_use_to_develop
db.url=jdbc:postgresql://localhost:5432/tipdm_hb
#db.url=jdbc:postgresql://192.168.0.93:5432/tipdm_hb_2_22_bak
db.driver=org.postgresql.Driver
db.user=postgres
db.password=root