input {
  elasticsearch {
    hosts => ["192.168.2.162:9200","192.168.111.76:9200","192.168.111.77:9200"]
    index => "order_index_v3"
    query => '{ "query": { "query_string": { "query": "*" } } }'
    size  => 100
    scroll => "1m"
	schedule => "*/30 * * * *"
  }
}
output {
  stdout { codec => json }
  kafka {
    codec => json
    topic_id => "order"
	bootstrap_servers => "192.168.111.76:9092,192.168.111.77:9092,192.168.111.78:9092"
  }
}
