## spark engine configuration

## for SparkConf
spark.master=spark://server3:6066
spark.executor.memory=3g
spark.executor.cores=4
spark.cores.max=16
spark.driver.memory=2g
spark.driver.cores=2
#spark.executor.extraClassPath=hdfs://192.168.111.73:8020/user/root/law_project/law_project-1.0.jar
spark.executor.extraClassPath=local:///opt/law_project/law_project-1.0.jar:local:///data/spark_exjars/mysql-connector-java-5.1.45-bin.jar
spark.driver.extraClassPath=hdfs://192.168.111.73:8020/user/root/law_project/law_project-1.0.jar
spark.files=hdfs://192.168.111.73:8020/user/root/hive-site.xml


# extra jars
spark.appResource=hdfs://192.168.111.73:8020/user/root/law_project/law_project-1.0.jar
